### ISSUE TITLE
Incluir descargas mapas

### ISSUE THREAD

**Issue by ajpelu** [iramosgutierrez/afliber#1]
hola @iramosgutierrez y @h-lima. 
en primer lugar Enhorabuena por vuestro trabajo. Me parece una herramienta muy necesaria, puesto que los que hemos trabajado con algunos taxones, siempre acudimos en primer lugar a la Flora Ibérica. El hecho de tener esa información disponible me parece muy muy interesante.

Sobre la app creada en shiny, creo que se podría enriquecer si además de generar la el mapa de distribución, se ofreciera la tabla asociada a esa búsqueda, es decir, una tabla con los datos para la especie. Y también creo que estaría genial si se pudiera dar la opción de descargar el shapefile asociado. Estas dos opciones no serían muy complicadas de implementar y ayudarían mucho. 

Un saludo
AntonioJ

**Comment by iramosgutierrez** [comment]
Muy buenas Antonio!
tienes toda la razón, creo que es una gran idea. La verdad es que es la primera vez que me ponía con estas cosas y me había quedado en el mapa, pero a raíz de tu comentario me he puesto con ello y ya está implementado.
¡Muchas gracias!
Ignacio.

**Comment by ajpelu** [comment]
Genial. Gracias por implementarlo y por hacerlo tan rápido. Un saludo.
